// Sample data for frontend development and demo
// This simulates the API response when the backend isn't connected

export const sampleCategories = [
  { id: 1, name: 'SaaS', slug: 'saas', count: 45 },
  { id: 2, name: 'E-Commerce', slug: 'ecommerce', count: 62 },
  { id: 3, name: 'Content', slug: 'content', count: 38 },
  { id: 4, name: 'Marketplace', slug: 'marketplace', count: 18 },
  { id: 5, name: 'Agency', slug: 'agency', count: 12 },
  { id: 6, name: 'App', slug: 'app', count: 24 },
];

export const sampleListings = [
  {
    id: 1,
    title: 'CloudSync Pro - B2B SaaS Platform',
    description: 'Established B2B SaaS platform providing cloud synchronization solutions for mid-market companies. Fully automated with minimal owner involvement. Strong MRR growth with low churn rate. 500+ active subscribers across 12 countries. Built with React and Node.js, hosted on AWS.',
    category: 'SaaS',
    asking_price: 850000,
    monthly_revenue: 42000,
    monthly_profit: 31500,
    monthly_traffic: 85000,
    status: 'approved',
    featured: true,
    url: 'cloudsyncpro.com',
    age_months: 36,
    monetization: 'Subscription',
    tech_stack: 'React, Node.js, PostgreSQL, AWS',
    seller_notes: 'Looking to sell to focus on new venture. All systems automated. Full documentation provided.',
    financials: {
      revenue_trend: [38000, 39500, 40000, 41000, 41500, 42000],
      profit_trend: [28000, 29000, 29500, 30500, 31000, 31500],
      expenses: { hosting: 3500, marketing: 4000, tools: 1500, support: 1500 },
    },
    traffic_details: {
      sources: { organic: 55, paid: 20, direct: 15, referral: 10 },
      top_countries: ['USA', 'UK', 'Canada', 'Germany', 'Australia'],
    },
    created_at: '2026-04-15',
    user_id: 2,
  },
  {
    id: 2,
    title: 'FitGear Direct - Premium Fitness E-Commerce',
    description: 'High-performing e-commerce store selling premium fitness equipment and accessories. Strong brand presence with 25K+ Instagram followers. Dropshipping model with verified suppliers. Consistently growing revenue with seasonal peaks.',
    category: 'E-Commerce',
    asking_price: 320000,
    monthly_revenue: 28000,
    monthly_profit: 12600,
    monthly_traffic: 120000,
    status: 'approved',
    featured: true,
    url: 'fitgeardirect.com',
    age_months: 24,
    monetization: 'Product Sales',
    tech_stack: 'Shopify, Klaviyo, Facebook Ads',
    seller_notes: 'Turnkey operation. All supplier relationships included in sale.',
    financials: {
      revenue_trend: [22000, 24000, 25000, 26500, 27000, 28000],
      profit_trend: [9000, 10000, 10500, 11500, 12000, 12600],
      expenses: { cogs: 11000, marketing: 3000, tools: 900, shipping: 500 },
    },
    traffic_details: {
      sources: { paid: 45, organic: 25, social: 20, referral: 10 },
      top_countries: ['USA', 'Canada', 'UK'],
    },
    created_at: '2026-04-20',
    user_id: 3,
  },
  {
    id: 3,
    title: 'TechInsider - Technology News Blog',
    description: 'Authority tech blog with 500+ articles, strong SEO foundation, and diversified revenue. Earning through display ads, affiliate marketing, and sponsored posts. Ranked on first page for 200+ keywords.',
    category: 'Content',
    asking_price: 175000,
    monthly_revenue: 8500,
    monthly_profit: 7200,
    monthly_traffic: 350000,
    status: 'approved',
    featured: true,
    url: 'techinsider.blog',
    age_months: 48,
    monetization: 'Ads, Affiliate, Sponsored',
    tech_stack: 'WordPress, Mediavine, AWS',
    seller_notes: 'Content team in place. Most revenue is passive from existing content.',
    financials: {
      revenue_trend: [7000, 7500, 7800, 8000, 8200, 8500],
      profit_trend: [6000, 6300, 6500, 6800, 7000, 7200],
      expenses: { hosting: 200, writers: 800, tools: 300 },
    },
    traffic_details: {
      sources: { organic: 78, direct: 12, social: 7, referral: 3 },
      top_countries: ['USA', 'India', 'UK', 'Canada', 'Philippines'],
    },
    created_at: '2026-03-10',
    user_id: 4,
  },
  {
    id: 4,
    title: 'DesignSwap - Freelancer Marketplace',
    description: 'Niche marketplace connecting businesses with vetted freelance designers. 2,000+ registered designers, 500+ completed projects. Platform takes 15% commission on all transactions.',
    category: 'Marketplace',
    asking_price: 520000,
    monthly_revenue: 18000,
    monthly_profit: 13500,
    monthly_traffic: 65000,
    status: 'approved',
    featured: false,
    url: 'designswap.io',
    age_months: 30,
    monetization: 'Commission',
    tech_stack: 'Next.js, Python, PostgreSQL',
    seller_notes: 'Strong network effects. Growing user base with high retention.',
    financials: {
      revenue_trend: [14000, 15000, 15500, 16000, 17000, 18000],
      profit_trend: [10000, 11000, 11500, 12000, 12800, 13500],
      expenses: { hosting: 1500, marketing: 2000, support: 1000 },
    },
    traffic_details: {
      sources: { organic: 40, direct: 30, referral: 20, paid: 10 },
      top_countries: ['USA', 'UK', 'Germany', 'Australia'],
    },
    created_at: '2026-04-01',
    user_id: 5,
  },
  {
    id: 5,
    title: 'QuickLearn - Online Course Platform',
    description: 'Ed-tech platform offering coding bootcamps and tech courses. 3,000+ students enrolled. 15 self-paced courses with video content. Strong completion rates and student satisfaction.',
    category: 'SaaS',
    asking_price: 290000,
    monthly_revenue: 15000,
    monthly_profit: 11000,
    monthly_traffic: 45000,
    status: 'approved',
    featured: false,
    url: 'quicklearn.dev',
    age_months: 20,
    monetization: 'Course Sales, Subscription',
    tech_stack: 'React, Django, AWS, Stripe',
    seller_notes: 'All course content included. Automated marketing funnels in place.',
    financials: {
      revenue_trend: [11000, 12000, 13000, 13500, 14000, 15000],
      profit_trend: [8000, 8800, 9500, 10000, 10500, 11000],
      expenses: { hosting: 800, marketing: 2200, tools: 500, instructors: 500 },
    },
    traffic_details: {
      sources: { organic: 35, paid: 35, social: 20, referral: 10 },
      top_countries: ['USA', 'India', 'UK', 'Nigeria'],
    },
    created_at: '2026-04-10',
    user_id: 2,
  },
  {
    id: 6,
    title: 'PetBox Monthly - Pet Subscription Box',
    description: 'Curated monthly subscription box for pet owners. 1,200+ active subscribers. Average 8-month retention. Strong brand with engaged community on social media.',
    category: 'E-Commerce',
    asking_price: 180000,
    monthly_revenue: 22000,
    monthly_profit: 6600,
    monthly_traffic: 35000,
    status: 'approved',
    featured: false,
    url: 'petboxmonthly.com',
    age_months: 18,
    monetization: 'Subscription Box',
    tech_stack: 'Shopify, ReCharge, Mailchimp',
    seller_notes: 'All supplier contracts transferable. Warehouse fulfillment partner in place.',
    financials: {
      revenue_trend: [18000, 19000, 20000, 20500, 21000, 22000],
      profit_trend: [5000, 5400, 5800, 6000, 6300, 6600],
      expenses: { cogs: 11000, shipping: 2400, marketing: 1500, tools: 500 },
    },
    traffic_details: {
      sources: { social: 40, organic: 25, paid: 25, referral: 10 },
      top_countries: ['USA', 'Canada'],
    },
    created_at: '2026-03-25',
    user_id: 6,
  },
  {
    id: 7,
    title: 'SEOBolt Agency - Digital Marketing',
    description: 'Boutique digital marketing agency specializing in SEO and content marketing for SaaS companies. 12 retainer clients with average contract value of $3,500/month. Proven systems and processes.',
    category: 'Agency',
    asking_price: 420000,
    monthly_revenue: 42000,
    monthly_profit: 25200,
    monthly_traffic: 12000,
    status: 'approved',
    featured: false,
    url: 'seobolt.agency',
    age_months: 42,
    monetization: 'Retainer Fees',
    tech_stack: 'WordPress, Ahrefs, HubSpot',
    seller_notes: 'Team of 4 contractors willing to stay. All SOPs documented.',
    financials: {
      revenue_trend: [38000, 39000, 40000, 40500, 41000, 42000],
      profit_trend: [22000, 23000, 23500, 24000, 24500, 25200],
      expenses: { contractors: 12000, tools: 3000, marketing: 1800 },
    },
    traffic_details: {
      sources: { referral: 50, organic: 30, direct: 15, social: 5 },
      top_countries: ['USA', 'UK', 'Canada'],
    },
    created_at: '2026-04-05',
    user_id: 3,
  },
  {
    id: 8,
    title: 'MealPrep AI - Nutrition Planning App',
    description: 'AI-powered meal planning mobile app with 15,000+ downloads. Freemium model with 8% conversion to premium. Machine learning-based recipe recommendations and grocery list generation.',
    category: 'App',
    asking_price: 210000,
    monthly_revenue: 9500,
    monthly_profit: 7100,
    monthly_traffic: 28000,
    status: 'approved',
    featured: false,
    url: 'mealprepai.app',
    age_months: 14,
    monetization: 'Freemium, In-App Purchases',
    tech_stack: 'React Native, Python, Firebase',
    seller_notes: 'App on both iOS and Android. Growing organically through word of mouth.',
    financials: {
      revenue_trend: [6000, 7000, 7500, 8000, 8800, 9500],
      profit_trend: [4500, 5200, 5600, 6000, 6500, 7100],
      expenses: { hosting: 800, marketing: 1000, tools: 600 },
    },
    traffic_details: {
      sources: { organic: 45, social: 30, referral: 15, paid: 10 },
      top_countries: ['USA', 'UK', 'Australia', 'Canada'],
    },
    created_at: '2026-04-18',
    user_id: 4,
  },
];

export const sampleTestimonials = [
  {
    id: 1,
    name: 'Marcus Chen',
    role: 'Acquired SaaS Business',
    content: 'Sally made the entire acquisition process seamless. Found my perfect SaaS business and closed the deal in just 3 weeks. The due diligence support was invaluable.',
    rating: 5,
  },
  {
    id: 2,
    name: 'Sarah Williams',
    role: 'Sold E-Commerce Store',
    content: 'I was skeptical about selling online, but Sally\'s evaluation and marketing of my store exceeded expectations. Got 15% above my asking price!',
    rating: 5,
  },
  {
    id: 3,
    name: 'David Park',
    role: 'Serial Acquirer',
    content: 'I\'ve purchased 4 businesses through Sally. The quality of listings, transparency of data, and professionalism of the team is unmatched in the industry.',
    rating: 5,
  },
];

export const sampleStats = {
  totalListings: 847,
  totalSold: 523,
  totalUsers: 12400,
  totalVolume: 125000000,
};

export const sampleFAQs = [
  {
    question: 'How does the buying process work?',
    answer: 'Browse our curated marketplace, submit an inquiry on listings you\'re interested in, receive detailed financials and due diligence materials, negotiate terms, and close the deal with our support throughout the process.',
  },
  {
    question: 'How long does it take to sell a website?',
    answer: 'On average, listings sell within 30-60 days. Premium listings with strong financials often sell faster. Our team helps optimize your listing to attract qualified buyers.',
  },
  {
    question: 'What fees does Sally charge?',
    answer: 'We charge a success-based commission only when your business sells. For buyers, there are no fees. Seller commission rates vary based on the deal size, typically ranging from 8-15%.',
  },
  {
    question: 'How do you verify listings?',
    answer: 'Every listing goes through our rigorous vetting process. We verify financials, traffic data, and business operations. Only about 30% of submitted businesses make it to our marketplace.',
  },
  {
    question: 'Is my information kept confidential?',
    answer: 'Absolutely. Seller identities and sensitive business details are only shared with qualified, vetted buyers who have signed an NDA. We take confidentiality very seriously.',
  },
  {
    question: 'Can I get a free valuation of my website?',
    answer: 'Yes! Submit your website through our free evaluation form and our team will provide a comprehensive valuation within 3-5 business days.',
  },
];
